### ISSUE TITLE
[l10n-web] [mozilla.org]: firefox/all.lang

### ISSUE THREAD

**Issue by rowdymehul** [mozguj/L10n-gu-IN#1]
Hey Localizers,

Hope you all are doing good. 

> Project: firefox/all.lang
> Locales: same as Firefox for Desktop and Android
> **Deadline: 4 April**

Happy to invite all new localizers in the community to start with this project. 

The deadline is indicative. 

Link to contribute : https://pontoon.mozilla.org/gu-IN/mozillaorg/firefox/all.lang/?string=164160

Feel free to let us know if you need any help/questions. 

Thank you, 
Mehul Patel.
**On Behalf of [Mozilla Gujarat](http://blog.mozillagujarat.org/).**

**Comment by rowdymehul** [comment]
Just up update, progress reached to 61%. Cheers. Thanks @drashti4 for help.

**Comment by rowdymehul** [comment]
Reviewed some strings, current progress reached to 88%. Cheers!!! 👍  Great work team.

**Comment by drashti4** [comment]
and It's completed  :)

**Comment by rowdymehul** [comment]
Thanks @drashti4 . I have reviewed all the strings and corrected some strings. Please note that,  don't translate brand names (Firefox, Mozilla). I have seen that in many strings, for now I have corrected. 

I will mark this project as complete. Thanks everyone. 💯
