### ISSUE TITLE
[l10n-gu] Focus for Android

### ISSUE THREAD

**Issue by rowdymehul** [mozguj/L10n-gu-IN#15]
Hey Localizers,

Hope you all are doing good.

    Project: Focus for Android
    Deadline:  Sep 10, 2018 

https://pontoon.mozilla.org/gu-IN/focus-for-android/

We will be assigning the pending files to some active localizers, however happy to invite all new localizers in the community to start with this project.

Feel free to let us know if you need any help/questions.

P.S. Any suggestions or feedback's are always welcome. :100:

Thank you,
Mehul Patel.
On Behalf of Mozilla Gujarat.

**Comment by Siddhi5** [comment]
100% Done!

**Comment by rowdymehul** [comment]
Great Job team. :100:

**Comment by rowdymehul** [comment]
Closing this one. Thank everyone. :100:
