### ISSUE TITLE
Mozilla Pontoon Intro

### ISSUE THREAD

**Issue by herry121** [mozguj/L10n-gu-IN#17]
## Mozilla Pontoon Introduction

 - **Date:** 01/11/2018
 - **Location:** Harni-Virod Road, Vadodara, Virod, Gujarat - 390022
 - **Expected number of attendees:** 70

### List of talks:

Mozilla Introduction - Hariom Panchal (https://mozillians.org/en-US/u/Hariompanchal6079/) / Dhruv Pandit ()
Pontoon Introduction - Hariom Panchal (https://mozillians.org/en-US/u/Hariompanchal6079/)
Bugzilla Introduction - Mohammadyahya Mansuri (https://mozillians.org/en-US/u/mohmmadyahya010101/)

**Comment by rowdymehul** [comment]
Hi @herry121, 

I have registered the event on Reps portal, here is the link to RSVP: https://reps.mozilla.org/e/introduction-to-mozilla-pontoon-by-l10n-gu-team/

Also, sending you some swags for the event, that includes some Firefox and Mozilla logo stickers. 

All the best and let me know if you need any help. 

Cheers, 
Mehul Patel
