### ISSUE TITLE
Agenda - Mozilla l10n Gujarati Training Meetup 2018

### ISSUE THREAD

**Issue by rowdymehul** [mozguj/L10n-gu-IN#18]
## Goal: 
Agenda - Mozilla l10n Gujarati Training Meetup 2018

## Related Issues & Links: 
https://wiki.mozilla.org/India/Mozilla_Hindi_Marathi_Gujarati_Community_Meet-up_2018 #

New source: https://github.com/mozguj/L10n-gu-IN/wiki

## Roles:

Responsible: @rowdymehul @drashti4 

Accountable: @drashti4 

Supporting: @rowdymehul 

Consulted: @rowdymehul 

Informed: 

## Required: 
- [x] Agnda draft (owner, Due: Oct 15th) 
- [x] Review the Agenda (owner, Due: Oct 15th) 
- [x] Final Agenda Ready (owner, Due: Oct 16th)

**Comment by rowdymehul** [comment]
The schedule is drafted, link: https://github.com/mozguj/L10n-gu-IN/wiki/Mozilla-l10n-Gujarati-Training-Meetup-2018

Good work @meetpokar :+1:

**Comment by Hariom0311** [comment]
Can we add small sesion on github ?

**Comment by rowdymehul** [comment]
Sure @Hariom0311. Noted :+1:

**Comment by rowdymehul** [comment]
Reviewed the agenda and updated: https://github.com/mozguj/L10n-gu-IN/wiki/Mozilla-l10n-Gujarati-Training-Meetup-2018

This is open for the feedback. :+1:
