### ISSUE TITLE
[l10n-gu] firefox & firefox-for-android

### ISSUE THREAD

**Issue by rowdymehul** [mozguj/L10n-gu-IN#2]
Hey Localizers,

Hope you all are doing good. 

> Project: firefox-aurora & firefox-for-android-aurora
> **Deadline: Apr 17, 2017**

https://pontoon.mozilla.org/gu-IN/firefox/
https://pontoon.mozilla.org/gu-IN/firefox-for-android/

Happy to invite all new localizers in the community to start with this project. 

Feel free to let us know if you need any help/questions. 

P.S. Any suggestions or feedback's are always welcome. 💯 

Thank you, 
Mehul Patel.
**On Behalf of [Mozilla Gujarat](http://blog.mozillagujarat.org/).**

**Comment by haard10** [comment]
https://pontoon.mozilla.org/gu-IN/firefox-for-android-aurora/mobile/android/base/android_strings.dtd/?string=142065

I have translated some strings & also review my old strings @rowdymehul

**Comment by rowdymehul** [comment]
Hey @haard10 , Thanks for your translation, I have reviewed your some strings and updated some strings which sounds not formatted. Please note that changes for future translation. Rest will be reviewed soon, meantime just keep continuing your translation.

Feel free to ask if you have any questions or need any help. :)

Cheers!

**Comment by rowdymehul** [comment]
Current progress : 63%, way to go reach 100% 💯  Cheers!!!

**Comment by rowdymehul** [comment]
Updated Deadline :  Aug 07, 2017

**Comment by rowdymehul** [comment]
Updated Deadline :  Sep 20, 2017

**Comment by KotechaVishwa** [comment]
Suggested some strings of Firefox. @drashti / @rowdymehul please verify.

**Comment by rowdymehul** [comment]
Hey, @KotechaVishwa  Thanks for translating strings. I am reviewing your strings.  Will update here once it's reviewed.

**Comment by KotechaVishwa** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/dom.properties/?string=152039
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/device.properties/?string=77059
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/startup.properties/?string=155091
@rowdymehul My suggested string files. Please verify!

**Comment by rowdymehul** [comment]
Hey @KotechaVishwa ,

Done: https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/startup.properties/?string=155091

Suggestions: Don't translate access keys i.e T, B ,A etc. any character. 

Rest, I have corrected some your strings. Left files will be reviewed soon. 

Amazing work. Keep it up 💯

**Comment by rowdymehul** [comment]
Hey, all your 3 files are reviewed. :) Awesome job @KotechaVishwa

**Comment by KotechaVishwa** [comment]
Thank you @rowdymehul😊

**Comment by KotechaVishwa** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/pluginproblem/pluginproblem.dtd/?string=166755
I have suggested this complete file. @rowdymehul please review.

**Comment by KotechaVishwa** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/browser/extensions/onboarding/onboarding.properties/?string=168652
completed suggesting this too. @rowdymehul please review.

**Comment by Veerskyfire** [comment]
sharing my pontoon profile https://pontoon.mozilla.org/contributors/l38xtzueZu0LPbKPyzv7WR072qY/ translated many string and on the way to do more

**Comment by rowdymehul** [comment]
Reviewed 4 files! 

Current progress: 71%, way to go reach 100% 💯 Keep it up, guys!

**Comment by KotechaVishwa** [comment]
Hi,

https://pontoon.mozilla.org/gu-IN/mozillaorg/all-resources/?status=missing&string=174213 
All the remaining strings of this are completed. I request the testers to do the needful.
