### ISSUE TITLE
An Open session - Introduction to l10n

### ISSUE THREAD

**Issue by rowdymehul** [mozguj/L10n-gu-IN#21]
## Goal: 
Agenda - An Open session - Introduction to l10n

## Related Issues & Links: 
https://github.com/mozguj/L10n-gu-IN/wiki/Mozilla-l10n-Gujarati-Training-Meetup-2018

## Roles:

Responsible: @rowdymehul  

Accountable: @rowdymehul 

Supporting: @rowdymehul 

Consulted: @rowdymehul 

## Notes : 

* This is an open event so anyone can attend this session. 
P.S. Registration is required. 

* Link to register: https://goo.gl/forms/r2314H4Bv7a6TsIq1
* RSVP: https://www.facebook.com/events/1601921283243394 

## Required: 
- [x] Drafted  (owner, Due: Nov 22th)
- [x] Registration form released (owner, Due: Nov 10th)  
- [x] Event date (owner, Due: Dec 2nd)

**Comment by rowdymehul** [comment]
An open session has been lead by @meetpokar :1st_place_medal: 

https://twitter.com/rowdymehul/status/1069120106951778304

**Comment by meetpokar** [comment]
Thank You @rowdymehul for giving me a chance to lead an Open session at Mozilla l10n Gujarati training meetup 2018. It was a great experience for me to take the session. +1

**Comment by rowdymehul** [comment]
Anytime @meetpokar :100: 

Keep up the good work :+1:
