### ISSUE TITLE
[l10n-gu] Firefox Screenshots 

### ISSUE THREAD

**Issue by rowdymehul** [mozguj/L10n-gu-IN#3]
Hey Localizers,

Hope you all are doing good. 

> Project: firefox-aurora & firefox-for-android-aurora
> **Deadline: Apr 11, 2017**

https://pontoon.mozilla.org/gu-IN/firefox-screenshots/

Happy to invite all new localizers in the community to start with this project. 

Feel free to let us know if you need any help/questions. 

P.S. Any suggestions or feedback's are always welcome. 💯 

Thank you, 
Mehul Patel.
**On Behalf of [Mozilla Gujarat](http://blog.mozillagujarat.org/).**

**Comment by rowdymehul** [comment]
Hey All,

New deadline updated to  Apr 18, 2017.

**Comment by drashti4** [comment]
marked :100:

**Comment by rowdymehul** [comment]
Great job!
