### ISSUE TITLE
[l10n-gu] Mozilla.org

### ISSUE THREAD

**Issue by rowdymehul** [mozguj/L10n-gu-IN#5]
Hey Localizers,

Hope you all are doing good. 

> Project: Mozilla.org
> **Deadline: Sep 26, 2017**

https://pontoon.mozilla.org/gu-IN/mozillaorg/

Happy to invite all new localizers in the community to start with this project. 

Feel free to let us know if you need any help/questions. 

P.S. Any suggestions or feedback's are always welcome. 💯 

Thank you, 
Mehul Patel.
**On Behalf of [Mozilla Gujarat](http://blog.mozillagujarat.org/).**

**Comment by rowdymehul** [comment]
Hey @KotechaVishwa,

https://pontoon.mozilla.org/gu-IN/mozillaorg/firefox/features/send-tabs.lang/?string=171610
https://pontoon.mozilla.org/gu-IN/mozillaorg/firefox/features/sync.lang/?string=171624

These files assigning to you to complete the translation. Once done you can assign us to review. 

Thanks. :)

**Comment by KotechaVishwa** [comment]
Ok Mehul, I'll complete it as soon as possible.👍

**Comment by KotechaVishwa** [comment]
@rowdymehul I have completed the files you have attached above. I request either of the three @rowdymehul / @drashti4  / @moinshaikh  to review it please.
