### ISSUE TITLE
L10n Guide

### ISSUE THREAD

**Issue by KotechaVishwa** [mozguj/L10n-gu-IN#7]
According to me, we should have a guide or something like that so that the new contributors understand as in how to work on pontoon.

**Comment by peiying2** [comment]
@KotechaVishwa Is this what you are looking for? https://github.com/mozilla-l10n/localizer-documentation/tree/master/tools/pontoon

**Comment by KotechaVishwa** [comment]
Oh, yes! Thank you @peiying2.

**Comment by KotechaVishwa** [comment]
But then, can we include the things like how to get into file of each projects, instead of directly finding out the missing strings of the projects. Suggesting one file at a time would make it easier for the reviewers to review.

**Comment by rowdymehul** [comment]
Hey @KotechaVishwa , as we discussed in last meeting we will be creating the docs for the same. Meantime, you can refer the documentation which @peiying2 has shared here. 

Thanks, Keep contributing. :)

**Comment by rowdymehul** [comment]
Closing this one! Thanks. :)
