### ISSUE TITLE
Mozilla L10n-gu-IN hackathon for Firefox Project

### ISSUE THREAD

**Issue by rowdymehul** [mozguj/L10n-gu-IN#8]
Hi Team, 

Hope you all are doing good. 

As discussed in our last meeting, we have scheduled online Hackathon for Firefox Project. This hackathon  will be on **16th & 17th September.** The aim of this hackathon to do translation quality review, Style guide review, Work progress check and assignment.

Anyone can participate in this and ask us here if they need any help or have any questions. 

Project link: https://pontoon.mozilla.org/gu-IN/firefox/ 
Planing pad :  https://public.etherpad-mozilla.org/p/Mozilla_L10n-gu-IN_hackathon

> Registration link : https://goo.gl/forms/zdCVYtpX8WwkySYA2

**> DEADLINE :  Sep 20, 2017** 

Do not hesitate to contact us if you have any questions.

**Thanks & Regards,**
Mehul Patel.
**On behalf of Mozilla Gujarat.**

**Comment by rowdymehul** [comment]
Hey All,

I am assigning some files, once you completed do comment here: 

@Vishwa : 
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/inspector.properties/?string=76896
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/layout.properties/?string=166340
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/markers.properties/?string=90394
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/memory.properties/?string=142012

@Miten : 

https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/netmonitor.properties/?string=76977
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/performance.dtd/?string=90504
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/performance.properties/?string=90359
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/responsive.properties/?string=152037

@Viral : 

https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/toolbox.dtd/?string=77847
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/toolbox.properties/?string=76565
https://pontoon.mozilla.org/gu-IN/firefox/devtools/shared/gclicommands.properties/?string=81897
https://pontoon.mozilla.org/gu-IN/firefox/devtools/shared/gcli.properties/?string=81794
https://pontoon.mozilla.org/gu-IN/firefox/devtools/shared/gcli.properties/?string=81796

**Comment by rowdymehul** [comment]
Guys,

15 files marked as 100%.  Just keep it up so will complete other files as well. :100:

**Comment by 007Brij** [comment]
https://pontoon.mozilla.org/gu-IN/activity-stream-new-tab/all-resources/?status=missing&string=166618

**Comment by Veerskyfire** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/animationinspector.properties/

**Comment by Veerskyfire** [comment]
This all files are reviewed 
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/jit-optimizations.properties/
https://pontoon.mozilla.org/gu-IN/firefox/browser/chrome/overrides/netError.dtd/
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/layout.properties/
https://pontoon.mozilla.org/gu-IN/activity-stream-new-tab/all-resources/
https://pontoon.mozilla.org/gu-IN/firefox/browser/chrome/browser/preferences/preferences.properties/
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/aboutdebugging.properties/
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/animationinspector.properties/

**Comment by pratik0101** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/markers.properties/

**Comment by pratik0101** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/memory.properties/

**Comment by pratik0101** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/responsiveUI.properties/

**Comment by pratik0101** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/performance.properties/

**Comment by pratik0101** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/mozapps/extensions/update.properties/

**Comment by pratik0101** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/storage.properties/

**Comment by pratik0101** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/netmonitor.properties/

**Comment by pratik0101** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/performance.dtd/

**Comment by 007Brij** [comment]
https://pontoon.mozilla.org/gu-IN/mozillaorg/all-resources/?status=missing&string=171655

**Comment by 007Brij** [comment]
https://pontoon.mozilla.org/gu-IN/mozillaorg/all-resources/?status=missing&string=171655

**Comment by 007Brij** [comment]
https://pontoon.mozilla.org/gu-IN/mozillaorg/all-resources/?status=missing&string=171655

**Comment by 007Brij** [comment]
https://pontoon.mozilla.org/gu-IN/firefox-for-android/all-resources/?status=missing&string=71216

**Comment by rowdymehul** [comment]
@Veerskyfire @drashti4 can you please review this as I am away from my desk. :)

**Comment by 007Brij** [comment]
https://pontoon.mozilla.org/gu-IN/mozillaorg/all-resources/?status=missing&string=172126

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/webide.dtd/?string=77708

**Comment by 007Brij** [comment]
https://pontoon.mozilla.org/gu-IN/mozillaorg/all-resources/?status=missing&string=172265

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/webide.dtd/?string=77670

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/shared/gcli.properties/?string=81794

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/shim/key-shortcuts.properties/?string=169137

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/mozilla.dtd/?string=172092

**Comment by 007Brij** [comment]
https://pontoon.mozilla.org/gu-IN/firefox-screenshots/all-resources/?status=missing&string=172284

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/webide.properties/?string=77066

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/shared/debugger.properties/?string=81782

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/shared/gclicommands.properties/?string=135684

**Comment by 007Brij** [comment]
https://pontoon.mozilla.org/gu-IN/firefox-for-android/all-resources/?status=missing&string=172374

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/dom/chrome/accessibility/AccessFu.properties/?string=69297

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/browser/chrome/browser/aboutSessionRestore.dtd/?string=172046

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/browser/chrome/browser/browser.properties/?string=161592

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/browser/chrome/browser/preferences/preferences.properties/?string=171999

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/browser/chrome/browser/sanitize.dtd/?string=75011

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/debugger.properties/?string=76783

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/webconsole.properties/?string=161763

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/search/search.properties/?string=80161

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/mozapps/update/updates.dtd/?string=79882

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/mozapps/extensions/extensions.properties/?string=79221

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/shared/styleinspector.properties/?status=missing&string=90234

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/dom/chrome/accessibility/mac/accessible.properties/?status=missing&string=69547

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/fallbackMenubar.properties/?status=missing&string=80862

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/dom/chrome/appstrings.properties/?string=172036

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/narrate.properties/?status=missing&string=149679

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/animationinspector.properties/?status=missing&string=172406

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/inspector.properties/?string=154002

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/datetimebox.dtd/?string=165184

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/extensions.properties/?string=152066

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/contentAreaCommands.properties/?status=missing&string=161755

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/console.properties/?status=missing&string=81057

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/viewSource.properties/?status=missing&string=80858

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/mozapps/downloads/downloads.properties/?status=missing&string=161556

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/mozapps/extensions/extensions.dtd/?status=missing&string=79363

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/videocontrols.dtd/?status=missing&string=161670

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/textcontext.dtd/?status=missing&string=81563

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/resetProfile.properties/?status=missing&string=153091

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/printPreview.dtd/?status=missing&string=153021

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/regionNames.properties/?status=missing&string=135702

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/notification.dtd/?status=missing&string=161684

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/notification.dtd/?status=missing&string=161684

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/languageNames.properties/?status=missing&string=80478

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/findbar.properties/?status=missing&string=153870

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/findbar.dtd/?status=missing&string=81693

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/printdialog.properties/?status=missing&string=80934

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/filepicker.properties/?status=missing&string=80902

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/debugger.properties/?status=missing&string=172687

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/dom/chrome/layout/css.properties/?status=missing&string=69761

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/dom/chrome/layout/layout_errors.properties/?status=missing&string=149770

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/commonDialogs.properties/?status=missing&string=155057

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/browser/chrome/browser/sitePermissions.properties/?status=missing&string=173374

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/browser/extensions/formautofill/formautofill.properties/?string=173388

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/browser/chrome/browser/browser.properties/?status=missing&string=173402

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/browser/chrome/browser/preferences/preferences.properties/?status=missing&string=173444

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/debugger.properties/?status=missing&string=173410

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/shim/startup.properties/?status=missing&string=173464

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/alerts/alert.properties/?status=missing&string=135644

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/dom/chrome/layout/xbl.properties/?status=missing&string=155073

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/dom/chrome/netError.dtd/?status=missing&string=152063

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/dom/chrome/plugins.properties/?status=missing&string=69204

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/security/manager/chrome/pippki/pippki.properties/?status=missing&string=159906

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/security/manager/chrome/pippki/pippki.dtd/?status=missing&string=70432

**Comment by 007Brij** [comment]
https://pontoon.mozilla.org/gu-IN/fundraising/all-resources/?status=missing&string=92374

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/dom/chrome/security/csp.properties/?status=missing&string=153930

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/netwerk/necko.properties/?status=missing&string=163853

**Comment by 007Brij** [comment]
https://pontoon.mozilla.org/gu-IN/firefox-screenshots/all-resources/?status=missing&string=173681

**Comment by 007Brij** [comment]
https://pontoon.mozilla.org/gu-IN/firefox-for-android/all-resources/?status=missing&string=173700

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/debugger.properties/?status=missing&string=173704

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/inspector.properties/?status=missing&string=173665

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/layout.properties/?status=missing&string=173670

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/security/manager/chrome/pipnss/nsserrors.properties/?status=missing&string=70936

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/aboutProfiles.dtd/?status=missing&string=148445

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/toolkit/chrome/global/aboutNetworking.dtd/?status=missing&string=159774

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/mozillaorg/firefox/hub/home-quantum.lang/?status=missing&string=173047

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/mozillaorg/firefox/products/developer-quantum.lang/?status=missing&string=172962

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/mozillaorg/mozorg/home/index-quantum.lang/?status=missing&string=174025

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/mozillaorg/firefox/mobile.lang/?status=missing&string=173058

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/mozillaorg/firefox/new/quantum.lang/?status=missing&string=172709

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/mozillaorg/main.lang/?status=missing&string=174021

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/mozillaorg/firefox/nightly_firstrun.lang/?status=missing&string=8279

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/mozillaorg/firefox/whatsnew_57.lang/?status=missing&string=173636

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/devtools/client/animationinspector.properties/?status=missing&string=173669

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/activity-stream-new-tab/all-resources/?status=missing&string=174167

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/mozillians/LC_MESSAGES/django.po/?status=missing&string=167834

**Comment by mohmmadyahya010101** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/all-resources/?status=missing&string=81263

**Comment by 007Brij** [comment]
https://pontoon.mozilla.org/gu-IN/firefox-screenshots/all-resources/?status=missing&string=174180

**Comment by 007Brij** [comment]
https://pontoon.mozilla.org/gu-IN/fundraising/all-resources/?status=missing&string=174182

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/mozillians/all-resources/?status=fuzzy&string=167836

**Comment by bhattsameer** [comment]
https://pontoon.mozilla.org/gu-IN/sumo/LC_MESSAGES/djangojs.po/?string=149243

**Comment by bhattsameer** [comment]
https://pontoon.mozilla.org/gu-IN/sumo/LC_MESSAGES/django.po/?string=58438

**Comment by bhattsameer** [comment]
https://pontoon.mozilla.org/gu-IN/sumo/LC_MESSAGES/buddyup.po/?string=60511

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/mozillians/all-resources/?status=fuzzy&string=162292
https://pontoon.mozilla.org/gu-IN/mozillians/all-resources/?status=fuzzy&string=167832
https://pontoon.mozilla.org/gu-IN/mozillians/LC_MESSAGES/django.po/?status=missing&string=174455
https://pontoon.mozilla.org/gu-IN/firefox-screenshots/all-resources/?status=missing&string=174454

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/all-resources/?status=missing&string=174597

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/focus-for-android/app.po/?status=missing&string=169927

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/all-resources/?status=missing&string=176011

**Comment by Hariompanchal** [comment]
https://pontoon.mozilla.org/gu-IN/firefox/all-resources/?status=missing&string=176165
